// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/Sumarizzerrrr.png"
    | "/Untitled-1.png"
    | "/Vietcombank.svg"
    | "/archive.html"
    | "/background.js"
    | "/content-script.js"
    | "/content-scripts/chatgpt.js"
    | "/content-scripts/content.js"
    | "/content-scripts/coursera.js"
    | "/content-scripts/gemini.js"
    | "/content-scripts/grok.js"
    | "/content-scripts/perplexity.js"
    | "/content-scripts/udemy.js"
    | "/content-scripts/youtube-copy-transcript.js"
    | "/content-scripts/youtubetranscript.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/256.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/64.png"
    | "/icon/96.png"
    | "/libs/protobuf.min.js"
    | "/logo.svg"
    | "/pearl.webp"
    | "/popop.html"
    | "/prompt.html"
    | "/settings.html"
    | "/sidepanel.html"
    | "/wxt.svg"
    | "/youtube_transcript.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
