// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/Sumarizzerrrr.png"
    | "/archive.html"
    | "/background.js"
    | "/content-scripts/coursera.js"
    | "/content-scripts/udemy.js"
    | "/content-scripts/youtubetranscript.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/256.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/64.png"
    | "/icon/96.png"
    | "/prompt.html"
    | "/sidepanel.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
