<script>
  // @ts-nocheck
  import { onMount } from 'svelte'
  import { settings } from '@/stores/settingsStore.svelte.js'
  import { summaryState } from '@/stores/summaryStore.svelte.js'
  import {
    generateFollowUpQuestions,
    openDeepDiveChat,
  } from '@/services/deepDiveService.js'

  // Props
  let { summary, contentType, originalContent = null } = $props()

  // State
  let questions = $state([])
  let isGenerating = $state(false)
  let isExpanded = $state(false)
  let selectedQuestion = $state('')
  let customQuestion = $state('')
  let selectedProvider = $state('gemini')
  let isStartingChat = $state(false)
  let errorMessage = $state('')

  // Provider options
  const providerOptions = [
    { id: 'gemini', label: 'Gemini' },
    { id: 'chatgpt', label: 'ChatGPT' },
    { id: 'perplexity', label: 'Perplexity' },
    { id: 'grok', label: 'Grok' },
  ]

  onMount(() => {
    // Set default provider from settings
    selectedProvider = settings.defaultDeepDiveProvider || 'gemini'

    // Auto-generate questions if setting is enabled
    if (settings.autoGenerateDeepDiveQuestions) {
      handleGenerateQuestions()
    }
  })

  async function handleGenerateQuestions() {
    isGenerating = true
    errorMessage = ''
    questions = []

    try {
      const generatedQuestions = await generateFollowUpQuestions(summary)

      if (generatedQuestions && generatedQuestions.length === 3) {
        questions = generatedQuestions
        isExpanded = true // Auto-expand when questions are generated
      } else {
        errorMessage = 'Failed to generate questions. Please try again.'
      }
    } catch (error) {
      console.error('[DeepDiveSection] Error generating questions:', error)
      errorMessage = 'Failed to generate questions. Please try again.'
    } finally {
      isGenerating = false
    }
  }

  function handleQuestionClick(question) {
    selectedQuestion = question
    customQuestion = '' // Clear custom question when selecting a suggested one
  }

  async function handleStartChat() {
    // Validate: must have either selected question or custom question
    const question = customQuestion.trim() || selectedQuestion
    if (!question) {
      errorMessage = 'Please select a question or type your own.'
      return
    }

    isStartingChat = true
    errorMessage = ''

    try {
      const result = await openDeepDiveChat({
        provider: selectedProvider,
        question: question,
        summary: summary,
        pageTitle: summaryState.pageTitle,
        pageUrl: summaryState.pageUrl,
        originalContent: originalContent,
        contentType: contentType,
      })

      if (!result.success) {
        errorMessage = result.error || 'Failed to open chat. Please try again.'
      }
    } catch (error) {
      console.error('[DeepDiveSection] Error starting chat:', error)
      errorMessage = 'Failed to open chat. Please try again.'
    } finally {
      isStartingChat = false
    }
  }

  function toggleExpanded() {
    isExpanded = !isExpanded
  }
</script>

<div class="deep-dive-section mt-8 border-t border-border/50 pt-6">
  <!-- Header -->
  <button
    class="flex items-center gap-2 text-lg font-medium hover:text-primary transition-colors"
    onclick={toggleExpanded}
    aria-expanded={isExpanded}
  >
    <span class="text-xl">{isExpanded ? '▾' : '▸'}</span>
    <span>Dive Deeper 💡</span>
  </button>

  {#if isExpanded}
    <div class="mt-4 space-y-4">
      <!-- Generate Button (if no questions yet) -->
      {#if questions.length === 0 && !isGenerating}
        <button
          class="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 transition-colors disabled:opacity-50"
          onclick={handleGenerateQuestions}
          disabled={isGenerating}
        >
          ✨ Generate Questions
        </button>
      {/if}

      <!-- Loading state -->
      {#if isGenerating}
        <div class="flex items-center gap-2 text-muted-foreground">
          <div
            class="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin"
          ></div>
          <span>Generating questions...</span>
        </div>
      {/if}

      <!-- Question chips -->
      {#if questions.length > 0}
        <div class="space-y-2">
          <p class="text-sm text-muted-foreground">
            Select a question or type your own:
          </p>
          <div class="flex flex-wrap gap-2">
            {#each questions as question, index}
              <button
                class="px-3 py-2 text-sm border rounded-md transition-all {selectedQuestion ===
                question
                  ? 'bg-primary text-primary-foreground border-primary'
                  : 'bg-background hover:bg-accent border-border'}"
                onclick={() => handleQuestionClick(question)}
              >
                {question}
              </button>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Custom question input -->
      <div class="space-y-2">
        <textarea
          bind:value={customQuestion}
          placeholder="Type your own question..."
          class="w-full px-3 py-2 border border-border rounded-md bg-background text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary resize-none"
          rows="3"
          oninput={() => {
            if (customQuestion.trim()) {
              selectedQuestion = ''
            }
          }}
        ></textarea>
      </div>

      <!-- Provider selector + Submit button -->
      <div class="flex items-center gap-3 flex-wrap">
        <label class="text-sm text-muted-foreground">Chat on:</label>
        <select
          bind:value={selectedProvider}
          class="px-3 py-1.5 border border-border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary"
        >
          {#each providerOptions as provider}
            <option value={provider.id}>{provider.label}</option>
          {/each}
        </select>
        <button
          class="px-4 py-1.5 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 transition-colors disabled:opacity-50 flex items-center gap-2"
          onclick={handleStartChat}
          disabled={isStartingChat ||
            (!customQuestion.trim() && !selectedQuestion)}
        >
          {#if isStartingChat}
            <div
              class="w-4 h-4 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin"
            ></div>
          {:else}
            💬
          {/if}
          <span>Start Chat</span>
        </button>
      </div>

      <!-- Error message -->
      {#if errorMessage}
        <p class="text-sm text-destructive">{errorMessage}</p>
      {/if}
    </div>
  {/if}
</div>

<style>
  .deep-dive-section {
    animation: fadeIn 0.3s ease-in;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>
